version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    platform: linux/x86_64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      - ordersystem

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - ordersystem

  go-app:
    build: .
    container_name: go-app
    working_dir: /app
    ports:
      - "8080:8080"
      - "8000:8000"
      - "50051:50051"
    depends_on:
      - mysql
      - rabbitmq
    environment:
      - DB_DRIVER=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=orders
      - WEB_SERVER_PORT=:8000
      - GRPC_SERVER_PORT=50051
      - GRAPHQL_SERVER_PORT=8080
    networks:
      - ordersystem

networks:
  ordersystem:
    driver: bridge